export const CITY_PAGES = [
  {
    slug: 'knee-replacement-bikaner',
    city: 'Bikaner',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Bikaner — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay provides world-class knee replacement surgery for patients from Bikaner. Forbes World Record holder. 24,000+ successful surgeries. OPD camps held regularly in Bikaner.',
    h1: 'Knee Replacement Surgery for Bikaner Patients',
    intro: 'Dr. Dheeraj Dubay, based at Shalby Hospital Jaipur, regularly holds OPD camps for patients from Bikaner and surrounding areas including Nokha, Lunkaransar, and Deshnoke. With over 24,000 successful joint replacement surgeries, Dr. Dubay is the most trusted orthopaedic surgeon for patients travelling from Bikaner to Jaipur.',
    campNote: 'OPD camps are held in Bikaner regularly. Call +91-8955373205 to know the next camp date.',
    distance: '330 km from Jaipur',
    patientNote: 'Hundreds of patients from Bikaner have been successfully treated by Dr. Dubay.',
  },
  {
    slug: 'knee-replacement-agra',
    city: 'Agra',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Agra Patients — Dr. Dheeraj Dubay',
    description: 'Patients from Agra trust Dr. Dheeraj Dubay for knee and hip replacement surgery in Jaipur. Forbes World Record holder with 24,000+ surgeries.',
    h1: 'Knee Replacement Surgery for Agra Patients',
    intro: 'Dr. Dheeraj Dubay at Shalby Hospital Jaipur is the preferred choice for knee and hip replacement surgery for patients from Agra, Mathura, Firozabad, and the surrounding UP region. His Zero technique ensures patients are walking within 24 hours of surgery.',
    campNote: 'Patients from Agra can book a direct consultation at Shalby Hospital Jaipur. Call +91-8955373205.',
    distance: '240 km from Jaipur',
    patientNote: 'Over 1,800 patients from Agra have been successfully treated.',
  },
  {
    slug: 'knee-replacement-kota',
    city: 'Kota',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Kota — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay provides expert knee replacement surgery for patients from Kota, Bundi, and Jhalawar. OPD camps held regularly.',
    h1: 'Knee Replacement Surgery for Kota Patients',
    intro: 'Patients from Kota, Bundi, Jhalawar, and Baran regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Dr. Dubay holds the Forbes World Record for most joint replacement surgeries in a single day.',
    campNote: 'OPD camps are held in Kota regularly. Call +91-8955373205 for next dates.',
    distance: '245 km from Jaipur',
    patientNote: 'Over 1,100 patients from Kota have been successfully treated.',
  },
  {
    slug: 'knee-replacement-alwar',
    city: 'Alwar',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Alwar — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay is the top choice for knee replacement surgery for patients from Alwar, Bharatpur, and Eastern Rajasthan.',
    h1: 'Knee Replacement Surgery for Alwar Patients',
    intro: 'Patients from Alwar, Bharatpur, Dholpur, and Dausa find it convenient to visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur — just 160 km away. Dr. Dubay\'s minimally invasive Zero technique means faster recovery and shorter hospital stays.',
    campNote: 'Patients from Alwar can book direct consultation at Shalby Hospital. Call +91-8955373205.',
    distance: '160 km from Jaipur',
    patientNote: 'Over 450 patients from Alwar have been successfully treated.',
  },
  {
    slug: 'knee-replacement-ajmer',
    city: 'Ajmer',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Ajmer — Dr. Dheeraj Dubay',
    description: 'Expert knee and hip replacement surgery for patients from Ajmer, Kishangarh, and Beawar by Dr. Dheeraj Dubay.',
    h1: 'Knee Replacement Surgery for Ajmer Patients',
    intro: 'Ajmer patients have easy access to Dr. Dheeraj Dubay at Shalby Hospital Jaipur on the Ajmer Expressway — the hospital is located right on the highway making it highly accessible. Dr. Dubay has treated hundreds of patients from Ajmer, Kishangarh, and Beawar.',
    campNote: 'Book your consultation at Shalby Hospital Vaishali Nagar, directly on the Ajmer Expressway. Call +91-8955373205.',
    distance: '135 km from Jaipur',
    patientNote: 'Over 260 patients from Ajmer have been successfully treated.',
  },
  {
    slug: 'knee-replacement-sikar',
    city: 'Sikar',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Sikar — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay provides expert joint replacement surgery for patients from Sikar, Jhunjhunu, and Churu.',
    h1: 'Knee Replacement Surgery for Sikar Patients',
    intro: 'Patients from the Shekhawati region — Sikar, Jhunjhunu, and Churu — regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur. His Forbes World Record and multiple national awards make him the most trusted orthopaedic surgeon in the region.',
    campNote: 'OPD camps are held in Sikar and Jhunjhunu. Call +91-8955373205 for next camp dates.',
    distance: '110 km from Jaipur',
    patientNote: 'Hundreds of patients from the Shekhawati region have been successfully treated.',
  },
  {
    slug: 'hip-replacement-jaipur',
    city: 'Jaipur',
    procedure: 'Hip Replacement',
    title: 'Best Hip Replacement Surgeon in Jaipur — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay is Jaipur\'s leading hip replacement surgeon at Shalby Hospital. Minimally invasive techniques, fast recovery, 24,000+ surgeries.',
    h1: 'Hip Replacement Surgery in Jaipur',
    intro: 'Dr. Dheeraj Dubay at Shalby Multi-Specialty Hospital, Vaishali Nagar, Jaipur is the city\'s most experienced hip replacement surgeon. Using minimally invasive techniques and the latest implants, Dr. Dubay ensures patients recover faster with less pain.',
    campNote: 'Walk-in OPD available at Shalby Hospital Vaishali Nagar and Dr. Dubay Hip & Knee Clinic, Vidhyadhar Nagar. Call +91-8955373205.',
    distance: 'Based in Jaipur',
    patientNote: 'Thousands of Jaipur patients have been successfully treated.',
  },
  {
    slug: 'joint-replacement-surgeon-jaipur',
    city: 'Jaipur',
    procedure: 'Joint Replacement',
    title: 'Best Joint Replacement Surgeon in Jaipur — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay — Jaipur\'s top joint replacement surgeon. Forbes World Record holder. 24,000+ surgeries. Shalby Hospital Vaishali Nagar.',
    h1: 'Best Joint Replacement Surgeon in Jaipur',
    intro: 'With over 24,000 successful knee and hip replacement surgeries, Dr. Dheeraj Dubay is Jaipur\'s most experienced joint replacement surgeon. He holds the Forbes World Record for most joint replacement surgeries in a single day and has been awarded by the Health Minister of Rajasthan for three consecutive years.',
    campNote: 'OPD at Shalby Hospital Vaishali Nagar (Mon-Sat) and Dr. Dubay Hip & Knee Clinic Vidhyadhar Nagar. Call +91-8955373205.',
    distance: 'Based in Jaipur',
    patientNote: 'Thousands of patients from across North India have been successfully treated.',
  },
]
