export const CITY_PAGES = [
  {
    slug: 'knee-replacement-bikaner',
    city: 'Bikaner',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Bikaner — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay provides world-class knee replacement surgery for patients from Bikaner. Forbes World Record holder. 24,000+ successful surgeries. OPD camps held regularly in Bikaner.',
    h1: 'Knee Replacement Surgery for Bikaner Patients',
    intro: 'Dr. Dheeraj Dubay, based at Shalby Hospital Jaipur, regularly holds OPD camps for patients from Bikaner and surrounding areas including Nokha, Lunkaransar, and Deshnoke. With over 24,000 successful joint replacement surgeries, Dr. Dubay is the most trusted orthopaedic surgeon for patients travelling from Bikaner to Jaipur.',
    campNote: 'OPD camps are held in Bikaner regularly. Call +91-8955373205 to know the next camp date.',
    distance: '330 km from Jaipur',
    patientNote: 'Hundreds of patients from Bikaner have been successfully treated by Dr. Dubay.',
  },
  {
    slug: 'knee-replacement-agra',
    city: 'Agra',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Agra Patients — Dr. Dheeraj Dubay',
    description: 'Patients from Agra trust Dr. Dheeraj Dubay for knee and hip replacement surgery in Jaipur. Forbes World Record holder with 24,000+ surgeries.',
    h1: 'Knee Replacement Surgery for Agra Patients',
    intro: 'Dr. Dheeraj Dubay at Shalby Hospital Jaipur is the preferred choice for knee and hip replacement surgery for patients from Agra, Mathura, Firozabad, and the surrounding UP region. His Zero technique ensures patients are walking within 24 hours of surgery.',
    campNote: 'Patients from Agra can book a direct consultation at Shalby Hospital Jaipur. Call +91-8955373205.',
    distance: '240 km from Jaipur',
    patientNote: 'Over 1,800 patients from Agra have been successfully treated.',
  },
  {
    slug: 'knee-replacement-kota',
    city: 'Kota',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Kota — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay provides expert knee replacement surgery for patients from Kota, Bundi, and Jhalawar. OPD camps held regularly.',
    h1: 'Knee Replacement Surgery for Kota Patients',
    intro: 'Patients from Kota, Bundi, Jhalawar, and Baran regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Dr. Dubay holds the Forbes World Record for most joint replacement surgeries in a single day.',
    campNote: 'OPD camps are held in Kota regularly. Call +91-8955373205 for next dates.',
    distance: '245 km from Jaipur',
    patientNote: 'Over 1,100 patients from Kota have been successfully treated.',
  },
  {
    slug: 'knee-replacement-alwar',
    city: 'Alwar',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Alwar — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay is the top choice for knee replacement surgery for patients from Alwar, Bharatpur, and Eastern Rajasthan.',
    h1: 'Knee Replacement Surgery for Alwar Patients',
    intro: 'Patients from Alwar, Bharatpur, Dholpur, and Dausa find it convenient to visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur — just 160 km away. Dr. Dubay\'s minimally invasive Zero technique means faster recovery and shorter hospital stays.',
    campNote: 'Patients from Alwar can book direct consultation at Shalby Hospital. Call +91-8955373205.',
    distance: '160 km from Jaipur',
    patientNote: 'Over 450 patients from Alwar have been successfully treated.',
  },
  {
    slug: 'knee-replacement-ajmer',
    city: 'Ajmer',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Ajmer — Dr. Dheeraj Dubay',
    description: 'Expert knee and hip replacement surgery for patients from Ajmer, Kishangarh, and Beawar by Dr. Dheeraj Dubay.',
    h1: 'Knee Replacement Surgery for Ajmer Patients',
    intro: 'Ajmer patients have easy access to Dr. Dheeraj Dubay at Shalby Hospital Jaipur on the Ajmer Expressway — the hospital is located right on the highway making it highly accessible. Dr. Dubay has treated hundreds of patients from Ajmer, Kishangarh, and Beawar.',
    campNote: 'Book your consultation at Shalby Hospital Vaishali Nagar, directly on the Ajmer Expressway. Call +91-8955373205.',
    distance: '135 km from Jaipur',
    patientNote: 'Over 260 patients from Ajmer have been successfully treated.',
  },
  {
    slug: 'knee-replacement-sikar',
    city: 'Sikar',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon in Sikar — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay provides expert joint replacement surgery for patients from Sikar, Jhunjhunu, and Churu.',
    h1: 'Knee Replacement Surgery for Sikar Patients',
    intro: 'Patients from the Shekhawati region — Sikar, Jhunjhunu, and Churu — regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur. His Forbes World Record and multiple national awards make him the most trusted orthopaedic surgeon in the region.',
    campNote: 'OPD camps are held in Sikar and Jhunjhunu. Call +91-8955373205 for next camp dates.',
    distance: '110 km from Jaipur',
    patientNote: 'Hundreds of patients from the Shekhawati region have been successfully treated.',
  },
  {
    slug: 'hip-replacement-jaipur',
    city: 'Jaipur',
    procedure: 'Hip Replacement',
    title: 'Best Hip Replacement Surgeon in Jaipur — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay is Jaipur\'s leading hip replacement surgeon at Shalby Hospital. Minimally invasive techniques, fast recovery, 24,000+ surgeries.',
    h1: 'Hip Replacement Surgery in Jaipur',
    intro: 'Dr. Dheeraj Dubay at Shalby Multi-Specialty Hospital, Vaishali Nagar, Jaipur is the city\'s most experienced hip replacement surgeon. Using minimally invasive techniques and the latest implants, Dr. Dubay ensures patients recover faster with less pain.',
    campNote: 'Walk-in OPD available at Shalby Hospital Vaishali Nagar and Dr. Dubay Hip & Knee Clinic, Vidhyadhar Nagar. Call +91-8955373205.',
    distance: 'Based in Jaipur',
    patientNote: 'Thousands of Jaipur patients have been successfully treated.',
  },
  {
    slug: 'joint-replacement-surgeon-jaipur',
    city: 'Jaipur',
    procedure: 'Joint Replacement',
    title: 'Best Joint Replacement Surgeon in Jaipur — Dr. Dheeraj Dubay',
    description: 'Dr. Dheeraj Dubay — Jaipur\'s top joint replacement surgeon. Forbes World Record holder. 24,000+ surgeries. Shalby Hospital Vaishali Nagar.',
    h1: 'Best Joint Replacement Surgeon in Jaipur',
    intro: 'With over 24,000 successful knee and hip replacement surgeries, Dr. Dheeraj Dubay is Jaipur\'s most experienced joint replacement surgeon. He holds the Forbes World Record for most joint replacement surgeries in a single day and has been awarded by the Health Minister of Rajasthan for three consecutive years.',
    campNote: 'OPD at Shalby Hospital Vaishali Nagar (Mon-Sat) and Dr. Dubay Hip & Knee Clinic Vidhyadhar Nagar. Call +91-8955373205.',
    distance: 'Based in Jaipur',
    patientNote: 'Thousands of patients from across North India have been successfully treated.',
  },
  {
    slug: 'knee-replacement-bharatpur',
    city: 'Bharatpur',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Bharatpur Patients — Dr. Dheeraj Dubay',
    description: 'Patients from Bharatpur trust Dr. Dheeraj Dubay for knee replacement surgery in Jaipur. Forbes World Record holder. 24,000+ surgeries. OPD camps available.',
    h1: 'Knee Replacement Surgery for Bharatpur Patients',
    intro: 'Patients from Bharatpur, Deeg, Kaman, Nagar, Weir, and Pahari regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Jaipur is approximately 185 km from Bharatpur — about 3 hours by road — making it highly accessible for patients from this region. Dr. Dubay holds the Forbes World Record for most joint replacement surgeries in a single day and has been recognised as the Most Trusted Joint Replacement Surgeon of North India by the Central Health Minister.',
    campNote: 'OPD camps are held in Bharatpur regularly. Call +91-8955373205 for the next camp date and location.',
    distance: '185 km from Jaipur (approx. 3 hours)',
    patientNote: 'Over 550 patients from Bharatpur and surrounding areas have been successfully treated by Dr. Dubay.',
  },
  {
    slug: 'knee-replacement-jhunjhunu',
    city: 'Jhunjhunu',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Jhunjhunu Patients — Dr. Dheeraj Dubay',
    description: 'Expert knee replacement surgery for patients from Jhunjhunu, Pilani, and Shekhawati region by Dr. Dheeraj Dubay in Jaipur. Book consultation today.',
    h1: 'Knee Replacement Surgery for Jhunjhunu Patients',
    intro: 'Patients from Jhunjhunu, Pilani, Bissau, Nawalgarh, and across the Shekhawati region regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur. The Shekhawati region has a high prevalence of knee arthritis, and Dr. Dubay has treated hundreds of patients from this area. Jaipur is approximately 180 km from Jhunjhunu — about 2.5 to 3 hours by road.',
    campNote: 'OPD camps are held in Jhunjhunu and Sikar. Call +91-8955373205 for next camp dates.',
    distance: '180 km from Jaipur (approx. 2.5-3 hours)',
    patientNote: 'Hundreds of patients from the Shekhawati region have been successfully treated.',
  },
  {
    slug: 'knee-replacement-churu',
    city: 'Churu',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Churu Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Churu, Sardarshahar, Ratangarh by Dr. Dheeraj Dubay in Jaipur. Forbes World Record holder. Book today.',
    h1: 'Knee Replacement Surgery for Churu Patients',
    intro: 'Patients from Churu, Sardarshahar, Ratangarh, Rajgarh, and surrounding Shekhawati areas travel to Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Dr. Dubay regularly treats patients from this region and understands the specific needs of patients travelling from Churu and Bikaner division.',
    campNote: 'OPD camps are held in Churu periodically. Call +91-8955373205 for the next camp date.',
    distance: '225 km from Jaipur (approx. 3-3.5 hours)',
    patientNote: 'Over 320 patients from Churu have been successfully treated.',
  },
  {
    slug: 'knee-replacement-mathura',
    city: 'Mathura',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Mathura Patients — Dr. Dheeraj Dubay',
    description: 'Patients from Mathura and Vrindavan trust Dr. Dheeraj Dubay for knee replacement in Jaipur. Expert orthopaedic surgeon. 24,000+ surgeries. Book today.',
    h1: 'Knee Replacement Surgery for Mathura and Vrindavan Patients',
    intro: 'Dr. Dheeraj Dubay treats a significant number of patients from Mathura, Vrindavan, Kosikalan, and surrounding areas of Western UP. Many devotees from Mathura and Vrindavan who suffer from knee pain find it appropriate to seek treatment in Jaipur before or after their pilgrimage. Dr. Dubay\'s Zero technique allows patients to walk within 24 hours, making the return journey more comfortable.',
    campNote: 'OPD consultation camps are held in the Mathura-Agra region. Call +91-8955373205 for dates.',
    distance: '250 km from Jaipur (approx. 4 hours by road)',
    patientNote: 'Over 370 patients from the Mathura region have been successfully treated.',
  },
  {
    slug: 'knee-replacement-sawai-madhopur',
    city: 'Sawai Madhopur',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Sawai Madhopur Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Sawai Madhopur, Karauli, and Tonk by Dr. Dheeraj Dubay in Jaipur. Expert orthopaedic care. Book consultation.',
    h1: 'Knee Replacement Surgery for Sawai Madhopur Patients',
    intro: 'Patients from Sawai Madhopur, Karauli, Gangapur City, and Bonli regularly visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur. The region is approximately 120 km from Jaipur — under 2 hours by road — making it convenient for patients to access world-class orthopaedic care at Dr. Dubay\'s clinic.',
    campNote: 'Patients from Sawai Madhopur can access Dr. Dubay\'s OPD at Shalby Hospital Jaipur conveniently. Call +91-8955373205.',
    distance: '120 km from Jaipur (approx. 2 hours)',
    patientNote: 'Patients from Sawai Madhopur, Karauli, and surrounding areas regularly treated.',
  },
  {
    slug: 'knee-replacement-tonk',
    city: 'Tonk',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Tonk Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Tonk, Uniyara, and Malpura by Dr. Dheeraj Dubay in Jaipur. Expert orthopaedic surgeon. Book consultation today.',
    h1: 'Knee Replacement Surgery for Tonk Patients',
    intro: 'Tonk is just 100 km from Jaipur — making Dr. Dheeraj Dubay\'s clinic at Shalby Hospital one of the most accessible world-class orthopaedic facilities for Tonk patients. Patients from Tonk, Uniyara, Malpura, Niwai, and Deoli regularly visit Dr. Dubay for knee and hip replacement consultations.',
    campNote: 'Patients from Tonk can visit Dr. Dubay\'s OPD at Shalby Hospital Jaipur conveniently given the proximity. Call +91-8955373205.',
    distance: '100 km from Jaipur (approx. 1.5 hours)',
    patientNote: 'Patients from Tonk and surrounding areas regularly treated at Dr. Dubay\'s clinic.',
  },
  {
    slug: 'knee-replacement-dausa',
    city: 'Dausa',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Dausa Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Dausa, Bandikui, and Lalsot by Dr. Dheeraj Dubay in Jaipur. Convenient access, expert care. Book today.',
    h1: 'Knee Replacement Surgery for Dausa Patients',
    intro: 'Dausa district patients have excellent access to Dr. Dheeraj Dubay at Shalby Hospital Jaipur — just 55 km away via the Delhi-Mumbai Expressway. This short distance makes Dr. Dubay\'s world-class orthopaedic care one of the most convenient options for patients from Dausa, Bandikui, Lalsot, Mahwa, and Sikandara.',
    campNote: 'Patients from Dausa can access Shalby Hospital Jaipur in under an hour. Call +91-8955373205.',
    distance: '55 km from Jaipur (approx. 1 hour)',
    patientNote: 'Patients from Dausa regularly treated due to easy Jaipur proximity.',
  },
  {
    slug: 'knee-replacement-nagaur',
    city: 'Nagaur',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Nagaur Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Nagaur, Didwana, and Makrana by Dr. Dheeraj Dubay in Jaipur. Expert orthopaedic surgeon. Book today.',
    h1: 'Knee Replacement Surgery for Nagaur Patients',
    intro: 'Patients from Nagaur, Didwana, Makrana, Nawa, and Ladnun regularly travel to Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Nagaur district has a high prevalence of knee arthritis and Dr. Dubay\'s affordable, high-quality care makes him the preferred choice for patients from this region.',
    campNote: 'OPD camps are held in Nagaur periodically. Call +91-8955373205 for next dates.',
    distance: '180 km from Jaipur (approx. 3 hours)',
    patientNote: 'Patients from Nagaur and the Marwar region regularly treated.',
  },
  {
    slug: 'knee-replacement-hanumangarh',
    city: 'Hanumangarh',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Hanumangarh Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Hanumangarh, Sangaria, and Nohar by Dr. Dheeraj Dubay in Jaipur. Expert orthopaedic care. Book consultation.',
    h1: 'Knee Replacement Surgery for Hanumangarh Patients',
    intro: 'Patients from Hanumangarh, Hanumangarh Town, Sangaria, Nohar, Bhadra, and Rawatsar travel to Dr. Dheeraj Dubay at Shalby Hospital Jaipur for world-class knee and hip replacement surgery. Though the distance from Hanumangarh is approximately 350 km, many patients from this region prefer Dr. Dubay\'s expertise and the superior facilities at Shalby Hospital.',
    campNote: 'OPD camps are periodically held in the Hanumangarh and Ganganagar region. Call +91-8955373205.',
    distance: '350 km from Jaipur (approx. 5 hours)',
    patientNote: 'Patients from Northern Rajasthan including Hanumangarh and Ganganagar regularly treated.',
  },
  {
    slug: 'knee-replacement-pali',
    city: 'Pali',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Pali Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Pali, Sojat, and Marwar Junction by Dr. Dheeraj Dubay in Jaipur. Forbes World Record holder. Book today.',
    h1: 'Knee Replacement Surgery for Pali Patients',
    intro: 'Patients from Pali, Sojat, Marwar Junction, Bali, Raipur, and the Marwar region visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Pali is approximately 200 km from Jaipur — about 3 hours by road. Dr. Dubay\'s clinic provides complete support for out-of-city patients including accommodation guidance.',
    campNote: 'OPD camps are held in Pali and the Marwar region. Call +91-8955373205 for next camp dates.',
    distance: '200 km from Jaipur (approx. 3 hours)',
    patientNote: 'Patients from the Marwar region including Pali regularly treated.',
  },
  {
    slug: 'knee-replacement-dholpur',
    city: 'Dholpur',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Dholpur Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Dholpur, Bari, and Rajakhera by Dr. Dheeraj Dubay in Jaipur. Expert orthopaedic care. Book consultation today.',
    h1: 'Knee Replacement Surgery for Dholpur Patients',
    intro: 'Patients from Dholpur, Bari, Rajakhera, and Sarmathura have increasingly been seeking knee and hip replacement surgery at Dr. Dheeraj Dubay\'s clinic in Jaipur. Dholpur is approximately 270 km from Jaipur and has excellent road and rail connectivity. Dr. Dubay\'s expertise, modern facilities, and insurance support make him the preferred choice for patients from this eastern Rajasthan district.',
    campNote: 'Patients from Dholpur can travel to Jaipur or contact us for camp dates in the Bharatpur-Dholpur region. Call +91-8955373205.',
    distance: '270 km from Jaipur (approx. 4 hours)',
    patientNote: 'Patients from Dholpur and eastern Rajasthan regularly treated.',
  },
  {
    slug: 'knee-replacement-bundi',
    city: 'Bundi',
    procedure: 'Knee Replacement',
    title: 'Best Knee Replacement Surgeon for Bundi Patients — Dr. Dheeraj Dubay',
    description: 'Knee replacement surgery for patients from Bundi, Nainwa, and Indergarh by Dr. Dheeraj Dubay in Jaipur. Expert orthopaedic care. Book consultation today.',
    h1: 'Knee Replacement Surgery for Bundi Patients',
    intro: 'Patients from Bundi, Nainwa, Indergarh, Lakheri, and Keshoraipatan visit Dr. Dheeraj Dubay at Shalby Hospital Jaipur for knee and hip replacement surgery. Bundi is approximately 210 km from Jaipur — about 3 hours by road — and is well connected via Kota. Dr. Dubay regularly treats patients from the Hadauti region including Kota, Bundi, Baran, and Jhalawar.',
    campNote: 'OPD camps are held in Kota — easily accessible from Bundi. Call +91-8955373205 for next dates.',
    distance: '210 km from Jaipur (approx. 3 hours)',
    patientNote: 'Patients from the Hadauti region including Bundi regularly treated.',
  },
]
